{{
  config(
    materialized = 'view'
    )
}}

SELECT
    FCT.EVENT_TYPE,
    FCT.PUBLIC,
    FCT.CREATED_AT          AS EVENT_DATE,
    CAST(EXTRACT(YEAR FROM FCT.CREATED_AT) AS STRING)    AS EVENT_YEAR,
    CAST(EXTRACT(MONTH FROM FCT.CREATED_AT) AS STRING)   AS EVENT_MONTH,
    FORMAT_DATE('%a', FCT.CREATED_AT)                    AS WEEKDAY_SHORT,
    USR.USERNAME,
    USR.USER_TYPE,
    ORG.USERNAME    AS ORG_USERNAME,
    ORG.USER_TYPE   AS ORG_USER_TYPE,
    REPO.REPO_NAME,
    REPO.REPO_FULL_NAME,
    REPO.REPO_IS_PRIVATE,
    REPO.REPO_DESCRIPTION,
    REPO.REPO_IS_FORK,
    REPO.REPO_CREATED_AT,
    REPO.REPO_UPDATED_AT,
    REPO.REPO_PUSHED_AT,
    REPO.REPO_GIT_URL,
    REPO.REPO_STARGAZERS_COUNT,
    REPO.REPO_WATCHERS_COUNT,
    REPO.REPO_LANGUAGE,
    REPO.REPO_HAS_ISSUES,
    REPO.REPO_HAS_DOWNLOADS,
    REPO.REPO_HAS_WIKI,
    REPO.REPO_HAS_PAGES,
    REPO.REPO_FORKS_COUNT,
    REPO.REPO_OPEN_ISSUES_COUNT,
    REPO.REPO_FORKS,
    REPO.REPO_OPEN_ISSUES,
    REPO.REPO_WATCHERS,
    REPO.REPO_DEFAULT_BRANCH
FROM {{ ref("FCT_EVENTS") }} AS FCT
LEFT JOIN {{ ref("DIM_USER") }} AS USR
    ON FCT.ACTOR_ID = USR.USER_ID
LEFT JOIN {{ ref('DIM_USER') }} AS ORG
    ON FCT.ORG_ID = USR.USER_ID
LEFT JOIN {{ ref('DIM_REPO') }} AS REPO
    ON FCT.REPO_ID = REPO.REPO_ID